# DATA_Manipulation_and_Analysis_with_Numpy

In [ ]:
#create a numpy array from  a list

In [ ]:
import numpy as np

# create a 1d array from a list

arr1=np.array([1,2,3,4,5])
print(arr1)

#creating a 2D array from a list of list

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Creating Arrays with functions

In [ ]:
# creating an array of zeros
zeros= np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# creating an array of ones
ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# creating an array with a range of values
range_arr=np.arange(10,20)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
range_arr=np.arange(10,20,2)
print(range_arr)

[10 12 14 16 18]


In [ ]:
# creating an array with random variable
random_arr=np.random.random((3,4))
print(random_arr)

[[0.66194263 0.28075468 0.54002287 0.27743466]
 [0.76048582 0.66966748 0.05722172 0.88604324]
 [0.57174271 0.2447049  0.3557713  0.67196675]]


In [ ]:
random_arr=np.random.randint(10,20,(3,4))
print(random_arr)

[[19 18 13 15]
 [18 13 18 17]
 [17 12 10 15]]


# Basic Array Operations Elements wise operations

In [ ]:
# Elements wise addition
arr1
print(arr1+2)

[3 4 5 6 7]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr*2)

[ 2  4  6  8 10]


In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0]

1

In [ ]:
# arr[8]

In [ ]:
# element wise substraction

print(arr-1)

[0 1 2 3 4]


In [ ]:
# elements wise multiplication
print(arr*2)

[ 2  4  6  8 10]


In [ ]:
# elemenst wise divison
print(arr/2)

[0.5 1.  1.5 2.  2.5]


# Basic array operations mathematical functions

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr.sum())

15


In [ ]:
# square root

print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
# exponential
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
# logarithm
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# sine
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# indexing and slicing indexing

In [ ]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# accessing elements
print(arr[0])
print(arr[-1])

0
9


# indexing and.  slicing advanced indexing

In [ ]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# slicing array
print(arr[2:5])
print(arr[:5])
print(arr[5:])

[2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]


In [ ]:
print(arr[arr>5])

[6 7 8 9]


In [ ]:
print(arr[(arr>5) & (arr<8)])

[6 7]


In [ ]:
indices=[0,2,4]
print(arr[indices])

[0 2 4]


#Reshaping Transposing Reshaping Array

In [ ]:
reshape_arr=np.arange(10)
print(reshape_arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
reshaped=arr.reshape((5,2))
print(reshaped) # total no of elements =Row * columns

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Reshaping and Transposing Transposing Arrays

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
transposed=arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
print(np.sum(arr))

21


#Aggregation functions sum and mean

In [ ]:
# sum of all elements.
print(np.sum(arr))

21


In [ ]:
# sum along columns
print(np.sum(arr,axis=0))

[5 7 9]


In [ ]:
# sum along row
print(np.sum(arr,axis=1))

[ 6 15]


In [ ]:
# means of all elements
print(np.mean(arr))

3.5


# min and max

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# minimum value
print(np.min(arr))

1


In [ ]:
# maximum value
print(np.max(arr))

6


In [ ]:
# index of max value
print(np.argmax(arr))

5
